### PR TITLE
added a 'Recognize Path' panel to the Routes page

### PR DESCRIPTION
**Pull request by digitalmoksha**
I find it very helpful to be able to take a current path and pull the controller/action, so added to the Routes page.

### CODE REVIEW

**Comment by dgynn** [comment]
This is great. Can you add a rescue for `ActionController::RoutingError` to handle the case where the route is not found? Thanks!

**Comment by digitalmoksha** [comment]
yeah, no problem.  I'm working on getting engine routes recognized properly

**Comment by digitalmoksha** [comment]
It's more robust now, and will match routes in engines as well.  Though it doesn't actually match the tuttle routes, i'm not sure why.  But it's currently working well on a project with many engines.

**Comment by dgynn** [comment]
Looks great. Thanks for the first PR!

**Pull request merged**
